Fix a number of ShellCheck warnings
joknarf/nerdps1 pull request #6
Opened 2024-08-31 07:17 UTC by sicherha

I have put the script through ShellCheck and fixed the most conspicuous warnings - in particular those related to quoting, as unintended globbing and word splitting can lead to unforeseen consequences.

2024-09-02 21:01 UTC, joknarf requested changes
Hello, 
Thanks for your work,
Just a regression on `$ps1_b64opt` that must not be quoted, as some version of base64 must have no option (and not empty option), typically macOS base64.

2024-09-02 21:01 UTC, joknarf commented on nerdps1
> +        2|b64) ssh -t "$remote" "$@" ". <(echo $(ps1_sshcmd "$loginopts" "$customenv"| gzip -c| base64 "$ps1_b64opt") |base64 -d|gzip -dc)";;
```suggestion
        2|b64) ssh -t "$remote" "$@" ". <(echo $(ps1_sshcmd "$loginopts" "$customenv"| gzip -c| base64 $ps1_b64opt) |base64 -d|gzip -dc)";;
```

2024-09-02 21:01 UTC, joknarf commented on nerdps1
> +    (umask 077;echo "RemoteCommand . <(echo $(ps1_sshcmd "$loginopts" "$customenv"| gzip -c| base64 "$ps1_b64opt") |base64 -d|gzip -dc)" >"$ssh_config") || return 1
```suggestion
    (umask 077;echo "RemoteCommand . <(echo $(ps1_sshcmd "$loginopts" "$customenv"| gzip -c| base64 $ps1_b64opt) |base64 -d|gzip -dc)" >"$ssh_config") || return 1
```

2024-09-03 20:05 UTC, sicherha commented on nerdps1
> +        2|b64) ssh -t "$remote" "$@" ". <(echo $(ps1_sshcmd "$loginopts" "$customenv"| gzip -c| base64 "$ps1_b64opt") |base64 -d|gzip -dc)";;
Done.

2024-09-03 20:05 UTC, sicherha commented on nerdps1
> +    (umask 077;echo "RemoteCommand . <(echo $(ps1_sshcmd "$loginopts" "$customenv"| gzip -c| base64 "$ps1_b64opt") |base64 -d|gzip -dc)" >"$ssh_config") || return 1
Done.

2024-09-03 20:09 UTC, sicherha commented
> Hello, Thanks for your work, Just a regression on `$ps1_b64opt` that must not be quoted, as some version of base64 must have no option (and not empty option), typically macOS base64.

Good catch. I wonder if it would make sense to turn `ps1_b64opt` and `ps1_info_vars` from space-separated strings into arrays. While I'm not overly familiar with ksh, it seems that all three of Bash, Zsh and ksh do support the `"${myarray[@]}"` notation for expanding an array into an argument list while maintaining proper quoting per element.

2024-09-07 11:31 UTC, joknarf commented
> > Hello, Thanks for your work, Just a regression on `$ps1_b64opt` that must not be quoted, as some version of base64 must have no option (and not empty option), typically macOS base64.
> 
> Good catch. I wonder if it would make sense to turn `ps1_b64opt` and `ps1_info_vars` from space-separated strings into arrays. While I'm not overly familiar with ksh, it seems that all three of Bash, Zsh and ksh do support the `"${myarray[@]}"` notation for expanding an array into an argument list while maintaining proper quoting per element.

very good idea indeed, but losing busybox ash compatibility as no array support in ash

2024-09-07 19:57 UTC, joknarf approved these changes

2024-09-07 19:59 UTC, merged